export const servicePages = {
  "laptop-computer-repair": {
    name: "Laptop & computer repair",
    shortName: "Laptop repair",
    eyebrow: "Computer repair · Cape Town",
    title: "Get your computer working properly again.",
    description: "Diagnosis and practical repair options for laptops and desktop computers with power, display, performance, storage or board-level faults.",
    image: "/images/laptop-repair.jpg",
    imageAlt: "Technician carrying out a laptop circuit-board repair",
    symptoms: ["No power or no display", "Slow startup, freezing or crashes", "Liquid exposure", "Charging or USB port damage", "Storage failure or missing data", "Overheating and loud fans"],
    work: ["Fault diagnosis", "Storage and memory upgrades", "Power and charging repair", "Board-level repair", "Cooling service", "Data-recovery assessment"],
    bring: "Bring the charger if power or charging is part of the fault. Back up important data if the computer still starts.",
  },
  "tv-monitor-repair": {
    name: "TV & monitor repair",
    shortName: "TV repair",
    eyebrow: "Display repair · Cape Town",
    title: "Bring the picture back.",
    description: "Professional assessment for TVs and monitors with backlight, power, picture, sound or input faults.",
    image: "/images/diagnostics.jpg",
    imageAlt: "Electronics diagnostics tools used to assess a display fault",
    symptoms: ["Sound but no picture", "Dead or flashing standby light", "Dim, blue or uneven picture", "Lines, flicker or distorted image", "HDMI input problems", "Unexpected shutdowns"],
    work: ["Backlight diagnosis", "Power-supply repair", "Main-board assessment", "HDMI and input repair", "Monitor power faults", "Picture-fault assessment"],
    bring: "Send the brand, exact model number, screen size and a photo or short video of the symptom before transporting a large display.",
  },
  "gaming-console-repair": {
    name: "Gaming console repair",
    shortName: "Console repair",
    eyebrow: "Console repair · Cape Town",
    title: "Get back in the game.",
    description: "Diagnostics and repair for PlayStation, Xbox and Nintendo systems with HDMI, power, cooling, storage and board faults.",
    image: "/images/console-repair.jpg",
    imageAlt: "Gaming console opened for professional electronics repair",
    symptoms: ["No HDMI signal", "Damaged HDMI or power port", "Overheating or loud fan", "No power", "Storage errors", "Unexpected shutdowns"],
    work: ["HDMI port replacement", "Power-fault diagnosis", "Cooling service", "Storage assessment", "Connector repair", "Board-level diagnosis"],
    bring: "Bring the power cable and any accessory directly related to the fault. Keep unrelated controllers and games at home unless requested.",
  },
  "audio-equipment-repair": {
    name: "Audio equipment repair",
    shortName: "Audio repair",
    eyebrow: "Audio electronics · Cape Town",
    title: "Clear sound starts with accurate diagnosis.",
    description: "Assessment for amplifiers, receivers, powered speakers, mixers and studio equipment with power, output or distortion faults.",
    image: "/images/workbench.jpg",
    imageAlt: "Electronics workbench used for professional audio equipment repair",
    symptoms: ["No power", "One channel not working", "Distorted or intermittent sound", "Buzzing or unusual noise", "Protection-mode faults", "Damaged connectors or controls"],
    work: ["Power-stage diagnosis", "Output-fault assessment", "Connector repair", "Control and switch faults", "Component replacement", "Bench testing"],
    bring: "Include the matching power supply where applicable and describe the connected equipment and conditions when the fault appears.",
  },
  "board-level-repair": {
    name: "Board-level electronics repair",
    shortName: "Board-level repair",
    eyebrow: "Microsoldering · Cape Town",
    title: "Repair the fault—not the entire board.",
    description: "Component-level fault finding, microsoldering and connector repair for suitable electronic devices and circuit boards.",
    image: "/images/technician-work.jpg",
    imageAlt: "Microscope used for detailed board-level electronics repair",
    symptoms: ["Short circuit or no power", "Burnt or liquid-damaged components", "Charging-port damage", "Loose board connector", "Intermittent board fault", "Failed power rail"],
    work: ["Microscope inspection", "Short-circuit diagnosis", "Microsoldering", "Port and connector replacement", "Component replacement", "Power-rail testing"],
    bring: "Send the device or board details first. Board-level repairability depends on damage, documentation, previous work and parts availability.",
  },
};

export const serviceEntries = Object.entries(servicePages);
